name: Upload Code Coverage
on: [ push, pull_request ]

jobs:
  test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift 5.7
        uses: sersoft-gmbh/swifty-linux-action@v2
        with:
          release-version: 5.7
      - name: Run Tests
        run: swift test -v --enable-code-coverage
      - name: Generate Code Coverage
        run: ./.github/scripts/generate-code-coverage.sh
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./info.lcov
