name: Test and Upload Code Coverage
on: [ push, pull_request ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift
        uses: sersoft-gmbh/swifty-linux-action@v1.3.0
        with:
          release-version: 5.5
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: swift test -v --enable-code-coverage
      - name: Generate Code Coverage
        run: ./.github/scripts/generate-code-coverage.sh
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./info.lcov
