name: Test
on: [ push, pull_request ]

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Swift Version
        run: swift --version
      - name: Run Tests
        run: swift test
        
  ubuntu-latest-5_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift 5.5
        uses: sersoft-gmbh/swifty-linux-action@v2
        with:
          release-version: 5.5
      - name: Check Swift Version
        run: swift --version
      - name: Run Tests
        run: swift test
        
  ubuntu-latest-5_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift 5.6
        uses: sersoft-gmbh/swifty-linux-action@v2
        with:
          release-version: 5.6
      - name: Check Swift Version
        run: swift --version
      - name: Run Tests
        run: swift test
        
  ubuntu-latest-5_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift 5.7
        uses: sersoft-gmbh/swifty-linux-action@v2
        with:
          release-version: 5.7
      - name: Check Swift Version
        run: swift --version
      - name: Run Tests
        run: swift test
